# Generated by Django 6.0.3 on 2026-03-06 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pendingfarmer_alter_otprecord_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='language_preference',
            field=models.CharField(default='en', help_text="e.g., 'en', 'ta', 'hi'", max_length=10),
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_day', models.IntegerField(default=1)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('treatment_text', models.TextField()),
                ('sent_to_farmer', models.BooleanField(default=False)),
                ('farmer_photo_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='api.treatmentplan')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('plan', 'day_number')},
            },
        ),
    ]
