# Generated by Django 6.0.3 on 2026-03-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_conversation_chathistory_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='recovery_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pendingfarmer',
            name='recovery_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
